from marshmallow import Schema, fields


class GeneralSchema(Schema):
    state = fields.Str()
    city = fields.Str()
    zip_code = fields.Str()
    address = fields.Str()
    min_sqft = fields.Str()
    max_sqft = fields.Str()
    min_price = fields.Str()
    max_price = fields.Str()
    min_bed = fields.Str()
    max_bed = fields.Str()
    pricing_type = fields.Str()
    build_year = fields.Int()
    dog_friendly = fields.Bool()
    cat_friendly = fields.Bool()
    has_pool = fields.Bool()
    has_elevator = fields.Bool()
    has_fitness_center = fields.Bool()
    has_wheelchair_access = fields.Bool()
    has_dishwasher = fields.Bool()
    has_air_conditioning = fields.Bool()
    has_parking = fields.Bool()
    star_rating = fields.List(fields.Str())
    furnished = fields.Bool()
    has_laundry_facilities = fields.Bool()
    property_type = fields.Str()
    search_radius = fields.Str()
