from marshmallow import Schema, fields

__author__ = "Brandon Watts"
__credits__ = ['Jonathan Cary', 'Austin Green']
__license__ = 'MIT'
__version__ = '0.1'


class CostarApiMockSchema(Schema):
    pt_select_all = fields.Bool()
    pt_industrial = fields.Bool()
    pt_retail = fields.Bool()
    pt_shopping_center = fields.Bool()
    pt_multifamily = fields.Bool()
    pt_specialty = fields.Bool()
    pt_office = fields.Bool()
    pt_health_care = fields.Bool()
    pt_hospitality = fields.Bool()
    pt_sports_and_entertainment = fields.Bool()
    pt_land = fields.Bool()
    pt_residential_income = fields.Bool()
    pu_business_for_sale = fields.Bool()
    pu_user_properties = fields.Bool()
    pu_investment_properties = fields.Bool()
    condo_inclusion = fields.Str()  # Include, Only, and Exclude
    portfolio_inclusion = fields.Str()  # Include, Only, and Exclude
    country = fields.Str()
    states = fields.Str()
    markets = fields.Str()
    submarkets = fields.Str()
    county = fields.Str()
    city = fields.Str()
    zip_code = fields.Str()
    street_address = fields.Str()
    search_radius = fields.Int()
    price_minimum = fields.Decimal()
    price_maximum = fields.Decimal()
    pricing_type = fields.Str()  # Total $, $ Per Square Foot, $ Per Acre, or $ Per Unit
    building_size_minimum = fields.Decimal()
    building_size_maximum = fields.Decimal()
    building_size_metric = fields.Str()  # Square Foot or Square Meter
    lot_size_minimum = fields.Decimal()
    lot_size_maximum = fields.Decimal()
    lot_size_metric = fields.Str()  # Acres, Square Foot, Hectares, Square Meters
    bed_range_minimum = fields.Int()
    bed_range_maximum = fields.Int()
    cap_rate_minimum = fields.Decimal()
    cap_rate_maximum = fields.Decimal()
    year_built_minimum = fields.Int()
    year_built_maximum = fields.Int()
    listing_id = fields.Str()
    keywords = fields.Str()
    date_entered = fields.Str()  # All Dates, Last 24 Hours, Last 3 Days, Last Week, 2 Weeks, Month, 3 Months, Year
    property_status = fields.Str()  # Only Net-Leased Properties, Include Pending Sales, Only Distressed Properties, Only Property Auctions
    tenancy_single = fields.Bool()  # Single or Multiple
    air_conditioning = fields.Bool()
    in_unit_washer_and_dryer = fields.Bool()
    washer_and_dryer_hookups = fields.Bool()
    dishwasher = fields.Bool()
    wheelchair_access = fields.Bool()
    parking = fields.Bool()
    laundry_facilities = fields.Bool()
    fitness_center = fields.Bool()
    pool = fields.Bool()
    elevator = fields.Bool()
    dog_friendly = fields.Bool()
    cat_friendly = fields.Bool()
    furnished = fields.Bool()
    apartments = fields.Bool()
    houses = fields.Bool()
    condos = fields.Bool()
    townhomes = fields.Bool()
    five_star = fields.Bool()
    four_star = fields.Bool()
    three_star = fields.Bool()
    two_star = fields.Bool()
    senior_housing = fields.Bool()
    military_housing = fields.Bool()
    student_housing = fields.Bool()
    corporate_housing = fields.Bool()
    affordable = fields.Bool()
    luxury = fields.Bool()
    cheap = fields.Bool()
    short_term = fields.Bool()
    square_feet_minimum = fields.Str()
    square_feet_maxiumum = fields.Str()
